name = "invitehub"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "invitehub-db"
database_id = "ede8596e-4a4c-4501-88f7-dc046f46a076"
